'use client';

import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';
import { FitnessPlan, UserProfile } from '@/lib/types';

Font.register({
  family: 'Helvetica',
  fonts: [
    { src: 'https://fonts.gstatic.com/s/helveticaneue/v70/1Ptsg8zYS_SKggPNyC0IT4ttDfA.ttf' },
    { src: 'https://fonts.gstatic.com/s/helveticaneue/v70/1Ptsg8zYS_SKggPNyC0IT4ttDfA.ttf', fontWeight: 'bold' },
  ]
});

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica' },
  header: { marginBottom: 20, textAlign: 'center' },
  title: { fontSize: 24, marginBottom: 10, fontWeight: 'bold', color: '#1a365d' },
  subtitle: { fontSize: 12, color: '#4a5568', marginBottom: 20 },
  sectionTitle: { fontSize: 18, marginTop: 15, marginBottom: 10, color: '#2b6cb0', borderBottom: '1px solid #e2e8f0', paddingBottom: 5 },
  dayContainer: { marginBottom: 10, padding: 10, backgroundColor: '#f7fafc', borderRadius: 4 },
  dayTitle: { fontSize: 14, fontWeight: 'bold', marginBottom: 5 },
  listItem: { fontSize: 10, marginBottom: 3, marginLeft: 10 },
  quoteBox: { marginVertical: 15, padding: 15, backgroundColor: '#fffaf0', borderLeft: '3px solid #ed8936' },
  quoteText: { fontSize: 12, fontStyle: 'italic', color: '#7c2d12' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 10, textAlign: 'center', color: '#a0aec0' }
});

interface PDFDocumentProps {
  plan: FitnessPlan;
  profile: UserProfile;
}

export const MyPlanPDF = ({ plan, profile }: PDFDocumentProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      
      <View style={styles.header}>
        <Text style={styles.title}>{profile.name}'s Fitness Plan</Text>
        <Text style={styles.subtitle}>Goal: {profile.goal} | Level: {profile.level} | {profile.location}</Text>
      </View>

      <View style={styles.quoteBox}>
        <Text style={styles.quoteText}>"{plan.motivationQuote}"</Text>
      </View>

      <Text style={styles.sectionTitle}>Weekly Workout Routine</Text>
      {plan.workoutPlan.map((day, i) => (
        <View key={i} style={styles.dayContainer}>
          <Text style={styles.dayTitle}>{day.day} - {day.focus}</Text>
          {day.exercises.map((ex, j) => (
            <Text key={j} style={styles.listItem}>
              • {ex.name}: {ex.sets} sets x {ex.reps} ({ex.rest} rest)
            </Text>
          ))}
        </View>
      ))}

      <Text break style={styles.sectionTitle}>Weekly Meal Plan</Text>
      {plan.dietPlan.map((day, i) => (
        <View key={i} style={styles.dayContainer}>
          <Text style={styles.dayTitle}>{day.day}</Text>
          {day.meals.map((meal, j) => (
            <Text key={j} style={styles.listItem}>
              • {meal.type}: {meal.name} - {meal.description}
            </Text>
          ))}
        </View>
      ))}

      <Text style={styles.footer}>Generated by AI Personal Coach • {new Date().toLocaleDateString()}</Text>
    </Page>
  </Document>
);